<?php
declare(strict_types=1);

namespace SeoEngine\Models;

use SeoEngine\Config;

final class KeywordData
{
    public string $keyword;
    public int    $searchVolume;
    public string $difficulty;

    public string $intent             = '';
    public string $funnel             = '';

    public float $businessValue       = 0.0;
    public float $rankingOpportunity  = 0.0;
    public float $topicalAuthority    = 0.0;
    public float $longTailScore       = 0.0;
    public float $trafficPotential    = 0.0;
    public float $revenuePotential    = 0.0;
    public float $serpOpportunity     = 0.0;
    public float $contentComplexity   = 0.0;
    public float $priorityScore       = 0.0;

    public string $cluster            = '';
    public string $pageType           = '';
    public string $urlSlug            = '';
    public string $suggestedH1        = '';
    public string $metaTitle          = '';
    public string $contentType        = '';
    public int    $wordCount          = 0;
    public string $schemaMarkup       = '';
    public string $internalLinkTargets = '';
    public string $roadmapPhase       = '';

    // Enhanced content strategy outputs (generated by ContentStrategyGenerator)
    public string $metaDescription     = '';
    public int    $readingTime         = 0; // minutes
    public string $suggestedHeadings   = ''; // pipe-separated H2/H3 suggestions
    public string $serpFeatureTargets  = ''; // pipe-separated list of SERP features to target
    public string $eeatRecommendations = ''; // short E-E-A-T action items
    public string $targetQuestions     = ''; // pipe-separated PAA / question targets
    public string $canonical           = '';

    public function __construct(string $keyword, int $searchVolume, string $difficulty)
    {
        $this->keyword      = $keyword;
        $this->searchVolume = $searchVolume;
        $this->difficulty   = $difficulty;
    }

    public function getDifficultyNumeric(): int
    {
        return Difficulty::toNumeric($this->difficulty);
    }

    public function getWordCount(): int
    {
        return count(explode(' ', $this->keyword));
    }

    public function getCtr(): float
    {
        return Config::CTR_BY_DIFFICULTY[$this->difficulty] ?? 0.10;
    }

    public function getConversionRate(): float
    {
        return Config::CONVERSION_RATES[$this->intent] ?? 0.005;
    }

    public function getPriorityClass(): string
    {
        if ($this->priorityScore >= 70) return 'high';
        if ($this->priorityScore >= 40) return 'medium';
        return 'low';
    }
}
